### ISSUE TITLE
Any plans for support for CRAM files ?

### ISSUE THREAD

**Issue by cmnbroad** [HadoopGenomics/Hadoop-BAM#24]
Or has anyone done any work on what it would take ?

**Comment by tomwhite** [comment]
I've had a brief look at what it would take to read CRAM files and I've posted some initial code here: https://github.com/HadoopGenomics/Hadoop-BAM/compare/master...tomwhite:cram (still needs tests).

The basic idea is to scan through the CRAM file to find all the container offsets. This should be fairly efficient since it is essentially a seek and a short read (to read the container header) for each container. This can be done in the implementation of InputFormat#getSplits, but if this turns out to be slow then it would be possible to write an index file, just like BAMInputFormat does.

Once the container offsets have been found then the file splits can be adjusted to align with the container boundaries. (So one split corresponds to one or more CRAM containers.) Then the record reader only needs to read the CRAM file header, before it reads the records from the containers in its split.

When reading CRAM files you need to have a reference file available. Currently, I've assumed it's on the local file system, but we really need something like https://github.com/samtools/htsjdk/pull/308 so the reference can be read from HDFS.

**Comment by cmnbroad** [comment]
Thx - I'll have a look.

**Comment by tomwhite** [comment]
Initial support was merged in https://github.com/HadoopGenomics/Hadoop-BAM/issues/28, with https://github.com/HadoopGenomics/Hadoop-BAM/issues/31 as a follow up. This issue can be closed now.
